Class {
	#name : #Gt2CodeblockSuccessfulEvaluationAnnouncement,
	#superclass : #Gt2CodeblockEvalutedAnnouncement,
	#instVars : [
		'result'
	],
	#category : #'GToolkit-NewDocumenter-Announcements'
}

{ #category : #accessing }
Gt2CodeblockSuccessfulEvaluationAnnouncement >> result [
	^ result
]

{ #category : #accessing }
Gt2CodeblockSuccessfulEvaluationAnnouncement >> result: anObject [
	result := anObject
]
