Extension { #name : #PRVisitor }

{ #category : #'*GToolkit-NewDocumenter' }
PRVisitor >> visitGt2ClassAnnotation: aGt2ClassAnnotation [ 
	self visitAnnotation: aGt2ClassAnnotation
]

{ #category : #'*GToolkit-NewDocumenter' }
PRVisitor >> visitGt2ExampleAnnotation: aGt2ExampleAnnotation [ 
	self visitAnnotation: aGt2ExampleAnnotation
]

{ #category : #'*GToolkit-NewDocumenter' }
PRVisitor >> visitGt2IcebergFileAnnotation: aGt2IcebergFileAnnotation [ 
	self visitAnnotation: aGt2IcebergFileAnnotation
]

{ #category : #'*GToolkit-NewDocumenter' }
PRVisitor >> visitGt2MethodAnnotation: aGt2MethodAnnotation [ 
	self visitAnnotation: aGt2MethodAnnotation
]
