Class {
	#name : #GtCodeblockSuccessfulEvaluationAnnouncement,
	#superclass : #GtCodeblockEvalutedAnnouncement,
	#instVars : [
		'result'
	],
	#category : #'GToolkit-Documenter-Announcements'
}

{ #category : #accessing }
GtCodeblockSuccessfulEvaluationAnnouncement >> result [
	^ result
]

{ #category : #accessing }
GtCodeblockSuccessfulEvaluationAnnouncement >> result: anObject [
	result := anObject
]
