"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestGToolkitNewDocumenter,
	#superclass : #PackageManifest,
	#category : 'GToolkit-Documenter-Manifest'
}

{ #category : #'code-critics' }
ManifestGToolkitNewDocumenter class >> ruleRBMissingTranslationsInMenusRuleV1FalsePositive [
	^ #(#(#(#RGPackage #(#'GToolkit-Documenter')) #'2018-11-10T11:51:24.749574-03:00') )
]
