Extension { #name : #PRVisitor }

{ #category : #'*GToolkit-Documenter' }
PRVisitor >> visitGtPillarExampleAnnotation: aGtPillarExampleAnnotation [ 
	self visitAnnotation: aGtPillarExampleAnnotation
]

{ #category : #'*GToolkit-Documenter' }
PRVisitor >> visitGtPillarExamplesAnnotation: aGtPillarExampleAnnotation [ 
	self visitAnnotation: aGtPillarExampleAnnotation
]

{ #category : #'*GToolkit-Documenter' }
PRVisitor >> visitGtPillarIcebergFileAnnotation: aGtPillarIcebergFileAnnotation [
	self visitAnnotation: aGtPillarIcebergFileAnnotation
]

{ #category : #'*GToolkit-Documenter' }
PRVisitor >> visitPillarClassAnnotation: aGtPillarClassAnnotation [ 
	self visitAnnotation: aGtPillarClassAnnotation
]

{ #category : #'*GToolkit-Documenter' }
PRVisitor >> visitPillarMethodAnnotation: aGtPillarMethodAnnotation [ 
	self visitAnnotation: aGtPillarMethodAnnotation
]
